### ISSUE TITLE
Additions for v1.0.0

### ISSUE THREAD

**Issue by Aunuxx** [CloudStrifera/MaCalc#5]
- [x] Grade overview #3 
- [x] Grade overview GPA #4 
- [x] Fix settings for Grade Average page #12 
- [x] What-if scores per category 0.7.0 #17 
- [x] New icon #4 
- [ ] Check systems for bugs 1.0.0
